### ISSUE TITLE
	2023-04-18 11:47:21.780	warn	TAG_EP_REQ_EP_RESERVE has no assigned polling interval - assuming 'M' - please check io-package.json

### ISSUE THREAD

**Issue by smartboart** [git-kick/ioBroker.e3dc-rscp#152]
Hello,
checked the setup and was also  not able to find the Tag: TAG_EP_REQ_EP_RESERVE 

**Describe the bug**  
Warn log message
<html><body>

  | 2023-04-18 11:47:21.780 | warn | TAG_EP_REQ_EP_RESERVE has no assigned polling interval  - assuming 'M' - please check io-package.json
-- | -- | -- | --

</body>
</html>
**To Reproduce**  
restarted the adapter with new log level / warn. since that i have this message.  Before i have logged some other things with silly level. 

Versions:

    Adapter version: 1.1.1
    JS-Controller version: 4.0.24
    Node version: v18.15.0
    Operating system: debian buster / RPI4 8GB
    NPM: 9.5.0

**Comment by git-kick** [comment]
Thanks for your report. This seems to be caused by a missing item in [io-package.json](https://github.com/git-kick/ioBroker.e3dc-rscp/blob/v1.1.1/io-package.json), where the polling intervals list is defined.
*But*: the entry for `TAG_EP_REQ_EP_RESERVE`was there in v1.1.1 already:
![grafik](https://user-images.githubusercontent.com/8932938/233849093-dfd80c77-87ce-44db-adde-98badc1808cb.png)

This issue has been fixed wit v1.0.8. Therefore, I suppose you missed the "Note"
![grafik](https://user-images.githubusercontent.com/8932938/233849629-1a931302-cba4-4c92-8621-1baae527d120.png)

Since the adapter settings infrastructure is "given" by ioBroker, I cannot work around this behavior.
Please start over with a "clean" adapter installation and do **not** import your settings from json.
Then it should work. If not, please post again.
