### ISSUE TITLE
 Unknown tag: tagCode=0x100003e, len=4, typeCode=0x7

### ISSUE THREAD

**Issue by mibr85** [git-kick/ioBroker.e3dc-rscp#210]
similar to #209 
i have the same issue every 5 min this massage come up:

e3dc-rscp.0 | 2024-03-08 06:15:17.042 | warn | Unknown tag: tagCode=0x100003e, len=4, typeCode=0x7
e3dc-rscp.0 | 2024-03-08 06:10:17.040 | warn | Unknown tag: tagCode=0x100003e, len=4, typeCode=0x7
e3dc-rscp.0 | 2024-03-08 06:05:17.039 | warn | Unknown tag: tagCode=0x100003e, len=4, typeCode=0x7
e3dc-rscp.0 | 2024-03-08 06:00:17.039 | warn | Unknown tag: tagCode=0x100003e, len=4, typeCode=0x7
e3dc-rscp.0 | 2024-03-08 05:55:17.037 | warn | Unknown tag: tagCode=0x100003e, len=4, typeCode=0x7
e3dc-rscp.0 | 2024-03-08 05:50:17.035 | warn | Unknown tag: tagCode=0x100003e, len=4, typeCode=0x7
e3dc-rscp.0 | 2024-03-08 05:45:17.038 | warn | Unknown tag: tagCode=0x100003e, len=4, typeCode=0x7

After restart of IOB container, problem is not solved.
What mean this warning?

After restart i can see this warnings:
e3dc-rscp.0 | 2024-03-08 11:26:37.070 | warn | TAG_EMS_REQ_EMERGENCY_POWER_TEST_STATUS has no assigned polling interval  - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2024-03-08 11:26:37.070 | warn | TAG_EMS_REQ_WB_ENFORCE_POWER_ASSIGNMENT has no assigned polling interval  - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2024-03-08 11:26:37.066 | warn | TAG_EMS_REQ_WB_DISCHARGE_BAT_UNTIL has no assigned polling interval  - assuming 'M' - please check io-package.json

I have a lot of MQTT connections and dont like to delet my instance because i lose all connections

**Comment by git-kick** [comment]
Part 1: `warn | Unknown tag: tagCode=0x100003e, len=4, typeCode=0x7`
This looks like your E3/DC device sends a tag which is (to my knowledge) not documented and thus cannot be decoded. This does not affect all other tags and values. I am happy to include the new tag if somebody can figure out what it is.

Part 2: `warn | TAG_EMS_REQ_... has no assigned polling interval - assuming 'M' - please check io-package.json`
I checked the current `io-package.json` and it contains all three listed tags. The warnings are normally due to re-use of an older adapter configuration which did not contain the tags (similar issue #191).
Please create a completely new adapter configuration (_not_ by importing a json) as described in the README under [Reuse of adapter configuration](https://github.com/git-kick/ioBroker.e3dc-rscp?tab=readme-ov-file#reuse-of-adapter-configuration).

**Comment by mibr85** [comment]
Is there an option to find out what the Unknown tag: tagCode=0x100003e, len=4, typeCode=0x7 means?

**Comment by git-kick** [comment]
`len=4, typeCode=0x7` says it is a `UInt32` value. About the meaning of `tagCode=0x100003e`, the developers at E3/DC know...
There is an official list of tag codes, and also a [tag-index](https://jnk-cons.github.io/easy-rscp/kdoc/easy-rscp/de.jnkconsulting.e3dc.easyrscp.api.frame.tags/index.html) by jnk, but this value is not listed yet.

**Comment by git-kick** [comment]
see v1.2.6, currently in beta repo

**Comment by flikflakandback** [comment]
Thank you for all the work you do for us! I tried to install v1.2.6 from the beta repo, but it didn't show up? Am I missing something?

**Comment by git-kick** [comment]
Sorry for that, I'm still struggling with the repo process (this time, I missed to update the copyright to 2024...). As I am on travel, I can't fix this short term. If you like, you can install v1.2.6 from github, using the URL https://github.com/git-kick/ioBroker.e3dc-rscp/tree/v1.2.6
